### PR TITLE
The Linkedin Package

### PR DESCRIPTION
**Pull request by diananeculai**
Partially solves the issue #83.

### CODE REVIEW

**Comment by drmmr763** [comment]
The only thing I know that the other folks are gonna say is to squash the commits.

**Comment by mbabker** [comment]
Nah, it looks like the history is the same as was merged into the Platform repo.  I merged her other packages that were transferred over the same way.

**Comment by diananeculai** [comment]
Yes, it's the same history as in the Platform. I made the PR for the Platform and thought I'd have time to squash some commits while waiting for feedback, but it was merged so fast that I never got the chance to do it.

**Comment by mbabker** [comment]
Feel free to squash some then if you've got time.  I don't do any merging from my work system, it's hard enough to just make my e-mail and GitHub load at times.

**Comment by diananeculai** [comment]
Done. Just 16 commits instead of 130 after squashing :-)

**Pull request merged**
