### PR TITLE
Fix PHPUnit test that fails on Windows

### PR DESCRIPTION
**Pull request by eirslett**
The assertion "Test appending with set()" in
vendor/Joomla/Database/Tests/QueryTest.php:1362 fails, because it's using
PHP_EOL in the test, and \n in the implementation. On Windows, PHP_EOL is
set to \r\n and so the test passes on Travis CI, but fails on Windows.
- Change implementation, use PHP_EOL instead of \n

### CODE REVIEW

**Comment by dongilbert** [comment]
Our Unit Testing tool, travis-ci.org, doesn't do testing in Windows environments. If @mbabker could confirm this failure and fix, I'd be happy to merge. Makes sense, of course. :+1:

**Comment by eirslett** [comment]
Just one thing I was worried about was; what is the actual intention? To use \n or to use PHP_EOL? Is it the test or the implementation that is wrong?

This is theoretical. Maybe it doesn't matter. But will any database treat \r\n whitespace different than \n?

**Comment by dongilbert** [comment]
I'm not sure, although I would assume PHP_EOL. This class existed before I
ever came around. :)

**Comment by mbabker** [comment]
@dongilbert You're going to make me finally dust off my Windows desktop to figure this out!?

The last I ran the Platform test suite on XAMPP 1.7.7 on Windows 7 64-bit, I had numerous errors that were due to OS differences.  Some effort was put into resolving those issues, but I can't remembered how we handled certain things.  The use of `realpath()` I do remember as one of those changes though.

**Comment by dongilbert** [comment]
Sorry. :(

I'm not aware of any other windows using maintainers. :)

**Comment by eddieajau** [comment]
Fixed - we use PHP_EOL in the rest of the file so this is a consistency problem.

**Pull request merged**
