### PR TITLE
Configure and enable Travis CI configuration for hhvm unit tests

### PR DESCRIPTION
**Pull request by ghost**
Adds hhvm to travis unit tests with failures allows.

Modifies invocation of phpcs and phpunit to use vendor supplied
copies[via composer] needed for hhvm to function.

Removes PEAR/PYRUS installs of phpcs and phpunit in favor of composer
installs.

Conflicts:
    composer.json

Signed-off-by: Gary A. Mort garyamort@gmail.com

### CODE REVIEW

**Comment by ghost** [comment]
Dependency: depends on https://github.com/joomla/joomla-framework/pull/334 for composer configuration
Replaces https://github.com/joomla/joomla-framework/pull/329 with partial implementation.

This implementation lacks corrections to tests and classes to enable running under hhvm.  It merely adds HHVM as a PHP version to test against.  The HHVM build is marked as ignored for purposes of "success".  

HHVM lacks PEAR/PYRUS so installs of phpunit, phpcs and other items are moved to Composer instead and ALL travis calls for phpunit and phpcs use the composer installed versions.

**Comment by ghost** [comment]
Replaced with https://github.com/joomla/joomla-framework/pull/335 for partial implementation.  Fixes will require separate pull requests/

**Comment by ghost** [comment]
Closed incorrect pull request, re-opened

**Comment by ghost** [comment]
My mistake...  it doesn't require 334, it can install cleanly on the current framework and runs "successfully".  By successfully I mean the current PHP 5.3 and 5.4 code sniffs and unit testing runs using the composer installed copies.  HHVM itself fails but it won't flag the build as failed.  Once this pull request is accepted, I can then cherry pick out the fixes from 329 - since they require changes for MANY different packages I'd prefer to wrap them up into individual pull requests for each package - especially since I am not positive the changes made for HHVM will not break tests for 5.3 or 5.4

**Comment by dongilbert** [comment]
We're restructuring a bit now, and will need to enable HHVM on packages where it makes sense (probably all of them). We'll let you know though, so stay tuned.

**Pull request closed without merging**
