### PR TITLE
Removed all @deprecated. Closes #18

### LINKED ISSUE #18: Clean all deprecated code
Any code marked with `@deprecated` needs to be removed. We are not supporting any deprecated code in the new Framework.

### PR DESCRIPTION
**Pull request by Skullbock**
This should be all for @deprecated

### CODE REVIEW

**Comment by eddieajau** [comment]
Something went amiss with the unit tests in this one. See https://travis-ci.org/joomla/joomla-framework/jobs/5157286

There were 2 errors:
1) ArchiveBzip2Test::testExtractWithStreams
array_push() expects parameter 1 to be array, null given

/home/travis/build/joomla/joomla-framework/vendor/Joomla/Filesystem/Stream.php:1476
/home/travis/build/joomla/joomla-framework/vendor/Joomla/Filesystem/Stream.php:587
/home/travis/build/joomla/joomla-framework/vendor/Joomla/Archive/Bzip2.php:102
/home/travis/build/joomla/joomla-framework/vendor/Joomla/Archive/tests/JArchiveBzip2Test.php:90

2) ArchiveGzipTest::testExtractWithStreams
array_push() expects parameter 1 to be array, null given

/home/travis/build/joomla/joomla-framework/vendor/Joomla/Filesystem/Stream.php:1476
/home/travis/build/joomla/joomla-framework/vendor/Joomla/Filesystem/Stream.php:587
/home/travis/build/joomla/joomla-framework/vendor/Joomla/Archive/Gzip.php:115
/home/travis/build/joomla/joomla-framework/vendor/Joomla/Archive/tests/JArchiveGzipTest.php:93

**Comment by Skullbock** [comment]
Yes, removing the errors variable set off a set of errors (my fault for not checking).
How the errors should be handled? now the Stream does $this->setError(). Better to use a throw RuntimeException?

**Comment by eddieajau** [comment]
> Better to use a throw RuntimeException

Yes, probably.

**Comment by Skullbock** [comment]
Let's see what Travis says now ;)

**Comment by eddieajau** [comment]
Close, but no cigar :)

PHP Parse error:  syntax error, unexpected ';' in /home/travis/build/joomla/joomla-framework/vendor/Joomla/Filesystem/Stream.php on line 1286

**Comment by Skullbock** [comment]
Now Travis reports that everything is ok ;)
https://travis-ci.org/joomla/joomla-framework/jobs/5160278

**Comment by eddieajau** [comment]
Done and dusted. Thanks!

**Pull request merged**
