### PR TITLE
Remove FTP support from Filesystem\File and Filesystem\Folder

### PR DESCRIPTION
**Pull request by dongilbert**
This also removes the ClientHelper class and tests as well as the ClientHelper references from Factory. This brings us one more step closer to dropping Factory as well.

Finally, this moves FtpClient out of the Client package and into Filesystem\Clients\FtpClient. If you need FTP support, use it directly, instead of through the File / Folder classes.

### CODE REVIEW

**Comment by dongilbert** [comment]
Once this and #229 is accepted, we can remove the Client folder.

**Comment by dongilbert** [comment]
This still needs some work for the tests to run stand alone. You currently can't `composer install` the dependencies, because they a circular reference. `Filesystem` requires `Log` and `Log` requires `Filesystem` at a stable version, so it can't use the one you're working on. 

It's weird.

But, good news is, running it as a full suite passes! (Probably thanks to the fact that most tests aren't implemented yet when it comes to `Filesystem`, but that's beside the point, right?)

**Comment by dongilbert** [comment]
OK, it seems that I was confusing the composer version resolver with the way I was doing the testing on it's own branch, that couldn't resolve to the required version. I ended up adding `"version": "1.0-beta2",` to the top of the `composer.json` in the `Filesystem` package, and composer was finally able to resolve all the dependencies and install. After that, I was able to wrap up the changes needed to make the `Filesystem` tests run stand alone.

**Comment by eddieajau** [comment]
:+1:

**Pull request merged**
