### PR TITLE
Adds documentation for the Joomla\Form\Form class

### PR DESCRIPTION
**Pull request by purplebeanie**
Sorry folks I've probably completely stuffed this PR.  It's my first attempt at this but just wanted to contribute back some documentation.  I notice when I compare I've got some of dongilbert's changes in here as well.

This adds some documentation about how to use for Joomla\Form\Form class, create XML and form validation rules.

Cheers,
Eric.

### CODE REVIEW

**Comment by dongilbert** [comment]
This is great! Ya, I can see you merged in the gh-pages branch, but it's easy enough to fix. Just do:

```
git checkout staging
git checkout -b NewFormDocs
git cherry-pick 5786b23b9499ee0eef3eb1ce0fe207d1ab5b3c5b
git branch -D formdocs
git checkout -b formdocs
git push -f origin formdocs
git branch -D NewFormDocs
```

Do that from within your local git repo, and it will remove the gh-pages merge, and force update this PR with just your contribution. 

Note: I'm on my mobile now, and this is untested, but should work fine.

**Comment by purplebeanie** [comment]
Haha! now I've got it!  Looks like it now is only showing the one file modified and the one commit!

**Comment by dongilbert** [comment]
Very cool. Thanks for clearing it up. Just formality now waiting for the build to finish.

**Comment by elkuku** [comment]
Awesome :+1:

**Pull request merged**
