### PR TITLE
[codestyle] Fixed casing in class/method/function names

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes the class/method/function names to comply with the CamelCase rules mentioned here:
http://joomla.github.io/coding-standards/?coding-standards/chapters/php.md

> ...be written in CamelCase even if using traditionally uppercase acronyms (such as XML, HTML).

### CODE REVIEW

**Comment by ghost** [comment]
Should I worry about Travis not passing? Seems like issues unrelated to this PR...

**Comment by mbabker** [comment]
This repo isn't the "home" anymore.  All of the packages got split out to https://github.com/joomla-framework

So who knows what state things are in here as far as CI services go.

**Comment by ghost** [comment]
Oops, ok. So PR towards wrong repo?
If so, why is this repo still up?

**Comment by ghost** [comment]
So if I would want to create PRs for the casing stuff towards the framework, I need to do that separately for every sub package?
Boy...

**Pull request closed without merging**
