### PR TITLE
Docs about using XML with Registry

### PR DESCRIPTION
**Pull request by piotr-cz**
I though I can load any XML file into registry, but you need to keep special format to do so.
My observations are in update to the Readme.md

### CODE REVIEW

**Comment by dongilbert** [comment]
Yeah, having to keep that format is a huge detriment to `Registry` IMO.

**Comment by piotr-cz** [comment]
I think it shouldn't be called `XML` which is misleading but `XMLdata` or such.

**Comment by eddieajau** [comment]
Awesome. Thanks.

**Comment by piotr-cz** [comment]
@eddieajau Thanks for your additions.

I wonder, if the node name should really be read from the attribute [`name`](https://github.com/joomla/joomla-framework/blob/staging/src/Joomla/Registry/Format/Xml.php#L67) or rather from [Node name](http://us3.php.net/manual/en/simplexmlelement.getname.php)

so this

``` XML
<?xml version="1.0"?>
<registry>
    <foo_1 type="string">bar</foo_1>
</registry>
```

would result in

```
Array (
    foo_1 => bar
)
```

Which brings us closer to how XML is generally used and open an option for full XML parser in future

**Comment by eddieajau** [comment]
No problem, I just saw that there were options there and I thought about writing a backlog item for it, and then it was more or less the same amount of time to write it out properly :)

On the other matter, I think that format works well with JSON, but XML is so bound to DTD's it makes it hard to do adhoc things. It also makes it hard on the importer because you can't use xpath and all that jazz.

**Comment by piotr-cz** [comment]
That's true.
It's just that when inside the code I prefer using `Registry` than `XML` methods and I was hoping to use it to parse REST outputs.

**Comment by eddieajau** [comment]
I know, but it seemed like a good idea at the time (late 2009) when Louis and I wrote the package :)

**Pull request merged**
