### PR TITLE
Don't try to close a connection that does not exist.

### PR DESCRIPTION
**Pull request by elinw**
This generates warnings when the connection does not exist. Instead, don't even try to close it.

### CODE REVIEW

**Comment by dongilbert** [comment]
What warnings are caused? It seems weird that it would have issues, simply because if `$this->connection` is not a valid Mysqli connection, then it will fail the `is_callable` check. In what situation are you getting errors?

Also, there is a syntax issue, so we are unable to run the tests to make sure it doesn't effect anything.

**Comment by realityking** [comment]
If we need to check if the connection is still alive, why don't we use the [ping method](http://php.net/manual/en/mysqli.ping.php) on the mysqli object?

**Comment by dongilbert** [comment]
Ping tries to connect if the connection has been dropped, so it may use resources unnecessarily. Also, we would have to make sure the connection is an instance of mysqli. 

Maybe instead of `is_callable(array($this->connection, 'close'))`, we should just do:

```
if ($this->connection instanceof \mysqli)
{
    $this->connection->close();
}
```

Also, there is a task to swap our mysqli with PDO, but I'm not sure if that's a 1.0 thing or if we're going to wait until 2.0.

**Comment by elinw** [comment]
You could try it, but this situation is not one where the connection has
unintentionally gone down, this is when as part of batch processing a large
volume of data potentially in the context of other limits, you have closed
and are now going to reopen so you have an empty object,. Anyway, I'm not
really of strong opinion about how to fix so long as it stops generating
warnings.

**Comment by elinw** [comment]
I really don't think fixing warnings should be delayed because of
hypothetical work.

**Comment by elinw** [comment]
It gives a warning that says cannot fetch mysqli. Which is true, it can't
when there is no connection. You actually see this pretty often if you use
var_dump a lot but in this case all the warnings are causing heavy
performance issues when batch processing such as is done in finder but also
of course in many high volume applications. the is_callable test is looking
at something different, as far as I can tell if the object exists  even if
totally empty, it will pass is_callable.
http://php.net/manual/en/function.is-callable.php
"Verify that the contents of a variable can be called as a function. This
can check that a simple variable contains the name of a valid function, or
that an array contains a properly encoded object and function name."

PHP Warning:  mysqli_close(): Couldn't fetch mysqli in ...\libraries\joo
mla\database\driver\mysqli.php on line 87

Anyway we've dealt with downstream but thought we might as well push
up since it is a clear error.

Also, there is error suppression nearby and I'm wondering if that was
related or was there for another reason; fixing this warning I didn't need
to suppress but I'm not sure if there was another reason for that.

In this case there is indeed an instance of mysqli, the problem is that it
is an empty instance.

If you want to see it in action you can try to run the cli indexer against
the correction: against the cms with the fix to this call that was previously merged but without this fix that also has been merged already,
 dumping out $this->connection.  Just ignore the
other errors which are unrelated.

**Comment by dongilbert** [comment]
I was making note of the task, since it's semi-relevant to this PR. If we do switch to PDO, then this PR can be closed now since we would handle it differently, and take care of the issue there.

Are you explicitly closing the connection outside of the API, and then deleting the object? If so, you should probably just delete the object and let the API take care of closing the connection.

Maybe we should do what rouven suggests and just use:

```
if ($this->connection instanceof \mysqli && $this->connection->ping())
{
    $this->connection->close();
}
```

Can you test that to see if it takes care of the warnings you are seeing?

**Comment by elinw** [comment]
You know what, I'm really not going to rewrite finder and most of the other queries in the cms because someday there might not be a mysqli driver. As I have said there are many many places where this warning is generated.  Yes if you don't care if the code is currently usable by all means close.

**Comment by elinw** [comment]
Can you explain how ping() will work if there is no database name, no user
name, no password and so on? I will certainly try it but it doesn't make a
lot of sense on the surface anymore than is_callable.
http://php.net/manual/en/mysqli.ping.php

See examples which all set those to actual values.

**Comment by AmyStephen** [comment]
@dongilbert Like @realityking said, Ping is likely the best way to go. I suppose a way to test it could be to add a unit test that connects, closes the connection, then runs the terminate code. If this can wait a week, I'll be happy to take it on next Wednesday.

**Comment by dongilbert** [comment]
Elin, ping WON'T work if that's the case, it will return false. Which, is exactly what we want to happen. Returning false, it won't run the mysqli close command, right?

**Comment by elinw** [comment]
Don sounds good then. But I think  we're deciding to  take a  totally
different approach anyway

Also if you were to leave __destruct using ping would be consistent with
https://github.com/joomla/joomla-cms/blob/master/libraries/joomla/database/driver/mysqli.php#L223

**Comment by dongilbert** [comment]
Were you able to test that suggestion, or you didn't bother? If not, I'll test it and see when I get a chance.

**Comment by elinw** [comment]
I'm at work and can't test until tonight, but if this is still in play when I get home I will test it.

**Comment by dongilbert** [comment]
Also: "Yes if you don't care if the code is currently usable by all means close." I'm not sure if you noticed, but we haven't tagged a beta release, let alone a stable release. There's probably more code than this that's not currently useable, although we have tried our best to prevent those, I'm sure some have slipped through.

We DO care about usability, but we also care about code quality. We don't want to push a potentially sub-optimal fix when there's time to do a little more research and make it right in the right way.

**Comment by elinw** [comment]
I have no problem with discussing the best way to fix, but if you really
are not going to fix it's just silly to even discuss.  In terms of ping
versus inspecting the object someone would really want to check the
performance side, but i'm sure in 99% of the cases the difference is
meaningless. There's another question of whether it is ever possible for
this not to be empty.

**Comment by AmyStephen** [comment]
@elinw Your patch has a syntax error. I will take this issue on for the framework.

**Comment by elinw** [comment]
update: no  ping doesn't  work e but I think probably we'll remove the whole method in the platform.

I don't know what "for the framework" means but i certainly don't need you to fix a syntax error in code we are likely not using though I' m sure it would be exciting to do so somehow. Have fun with it by all means.

**Comment by dongilbert** [comment]
So, the actual source of the error is here: https://github.com/joomla/joomla-framework/blob/staging/src/Joomla/Database/DatabaseQuery.php#L1414

When you (un)serialize the mysqli object, it does something weird to the connection and causes issues. If you look at the first note on the page here it sheds some light on the issue: http://php.net/manual/en/mysqli.query.php

When I read that, and saw his comment on serialize, I looked back at the XDebug stack trace and saw that there was a call to `unserialize` in the stack. Then, when I added a `__wakeup` method to the query obj with a `die('wat');` in it, I saw that the wakeup method was indeed being called. Traced it back to the method linked to above, did an early return, and everything came back no problems.

So, now the question becomes, why is that special `__clone()` method needed? It says it's to support large nested sets, but I'm not convinced it is needed.

**Comment by dongilbert** [comment]
And problem solved. Within the clone method foreach loop, add the key check as seen below, and make no other changes. Test and see if it doesn't fix your problem. :)

``` php
    /**
     * Method to provide deep copy support to nested objects and
     * arrays when cloning.
     *
     * @return  void
     *
     * @since   11.3
     */
    public function __clone()
    {
        foreach ($this as $k => $v)
        {
            if ($k === 'db')
            {
                continue;
            }

            if (is_object($v) || is_array($v))
            {
                $this->$k = unserialize(serialize($v));
            }
        }
    }
```

**Comment by elinw** [comment]
Ha i was just going to show you this https://github.com/joomla/joomla-platform/pull/570

CYou definitely need clone, deep cloning does not work otherwise.  Again it was finder that highlighted it as a missing piece in the code, but you need deep cloning in general to avoid scary motion at a distance.

http://php.net/manual/en/language.oop5.cloning.php

**Comment by dongilbert** [comment]
I'm not saying remove clone, I'm saying augment the `__clone` method so that it doesn't try to serialize and unserialize the `$db` var, which is what is causing the issue. The platform PR you linked to deals with the connection checking, not the root of the problem, which my fix above addresses. So, can you please try adding in the proposed change to the `JDatabaseQuery::__clone` method and see if it works for you? (I've tested, and it does, in fact, work.)

**Comment by elinw** [comment]
Yes but similar kind of circle and i wonder if the serialize has implications also. 

Yes that check does the trick! Excellent digging.

I was responding to the question at the end of your comment about why __clone is needed.

**Comment by dongilbert** [comment]
Well, this newfound solution should speed things up considerably, since the system is no longer serializing the db object.

Thanks. :)

**Comment by elinw** [comment]
Not to mention it solves this ancient and mysterious issue https://github.com/joomla/joomla-platform/issues/1167

**Comment by elinw** [comment]
Closing this one since we have a real solution.

**Comment by AmyStephen** [comment]
@elinw said, "update: no ping doesn't work e but I think probably we'll remove the whole method in the platform.

I don't know what "for the framework" means but i certainly don't need you to fix a syntax error in code we are likely not using though I' m sure it would be exciting to do so somehow. Have fun with it by all means."

My comment you are responding to "I will take this on for the framework." meant I was volunteering to help solve this problem. 

Thanks @dongilbert for fixing it. Thanks @elinw for raising the issue.

**Pull request closed without merging**
