### PR TITLE
Rewrite the profiler

### PR DESCRIPTION
**Pull request by florianv**
Rewrite the profiler :
- provide more methods
- decouple (un-hardcode) the rendering
- design it so it's easy to write/test a renderer
- 96% of coverage
- documentation updated

It should fix https://github.com/joomla/joomla-framework/issues/62, https://github.com/joomla/joomla-framework/issues/33, https://github.com/joomla/joomla-framework/issues/34

### CODE REVIEW

**Comment by dongilbert** [comment]
This is really good. Like, really good. And clean. I like it.

**Comment by florianv** [comment]
Thanks :)

I don't understand, when I made my first pull request, travis ran and it was passing.
After I merged the master, it didn't display anything anymore, I thought it was no more mergeable.

So I made a new pull request (this one) with a clean branch from the last Andrew's commit, but it looks like it is the same thing.

**Comment by dongilbert** [comment]
There's a backlog in travis right now, it's cued up and ready to run, we
just need to wait our turn.

**Comment by florianv** [comment]
ah ok :) I probably didn't have to close the first PR.

**Pull request merged**
