### PR TITLE
Add (string) before send text to ColorProcessor

### PR DESCRIPTION
**Pull request by asika32764**
To prevent user's mistake that sending a non-text variable to CliOutput.

### CODE REVIEW

**Comment by piotr-cz** [comment]
:+1:

**Comment by dongilbert** [comment]
I think a better approach would be to allow the processor to handle it. If you case it to a string first, you are restricting the possibilities for the processor. For example, you wouldnt be able to have an Exception Processor that outputs the stack trace, or some other nice message, since you are casting it to a string.

Just my thoughts on it. What do you think?

**Comment by asika32764** [comment]
Yes, I agree.

I just consider that we should check type in somewhere, because there are no checking now, the mistake will return error message to user, not a caught exception.

But if there will have some situation that user will hope to let processor handle it, we can use:

``` php
if (!is_string($string))
{
    throw new Exception('Need string');
}
```

In processor to notice developer send a right type, but this way cannot avoid error message.

Is there any other suggestion?

**Comment by eddieajau** [comment]
I agree with Don. The processor needs to do the final check on the argument passed to it.

**Comment by dongilbert** [comment]
Yes, I would do that checking in the output processor though, not in the method that sends data to the processor.

**Comment by dongilbert** [comment]
This PR is now out of scope, so I am going to close it, but thanks for submitting it because it prompted me to implement #315. Thanks @asika32764!

**Pull request closed without merging**
