### PR TITLE
Add raw filter

### PR DESCRIPTION
**Pull request by wilsonge**
See: https://groups.google.com/forum/?fromgroups#!topic/joomla-dev-cms/U_-u9wECKx8

### CODE REVIEW

**Comment by drmmr763** [comment]
Damn uni students have all this free time apparently! ;) nice! Is it just
me or is the "raw" doc block like item off kilter?

**Comment by wilsonge** [comment]
Haha. Just saying but I have a 9-5 job this year. I'm back to uni in September!! Have more time now than when I was at uni too .....

image

Umm looks OK to me - but feel free to correct me otherwise

**Comment by drmmr763** [comment]
Even in your screenshot the line for "raw" is off by a space it seems?

On Saturday, July 13, 2013, George Wilson wrote:

> Haha. Just saying but I have a 9-5 job this year. I'm back to uni in
> September!!
> 
> [image: image]https://f.cloud.github.com/assets/1986000/793577/24805656-ec1a-11e2-94e2-252655d27c99.png
> 
> Umm looks OK to me - but feel free to correct me otherwise
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joomla/joomla-framework/pull/185#issuecomment-20929233
> .

## 

Regards,
Chad Windnagle

**Comment by wilsonge** [comment]
image

Nope? It definately seems right to me!

**Comment by drmmr763** [comment]
Writing this from the pub so blame it on that. But the sentence:
"The raw..." in the doc block looks out of line with everything else.

On Saturday, July 13, 2013, George Wilson wrote:

> [image: image]https://f.cloud.github.com/assets/1986000/793580/037db07e-ec1b-11e2-9da3-3db5ffd63bb7.png
> 
> Nope? It definately seems right to me!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joomla/joomla-framework/pull/185#issuecomment-20929372
> .

## 

Regards,
Chad Windnagle

**Comment by wilsonge** [comment]
Ohhh bugger. That part. Was looking at the actual RAW bit. Will fix that
now :)

**Comment by wilsonge** [comment]
Fixed :) _facepalm_

**Comment by drmmr763** [comment]
Nice!

On Saturday, July 13, 2013, George Wilson wrote:

> Fixed :) _facepalm_
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joomla/joomla-framework/pull/185#issuecomment-20929500
> .

## 

Regards,
Chad Windnagle

**Pull request merged**
