### PR TITLE
Replace MySQL driver with PDO version #82

### PR DESCRIPTION
**Pull request by asika32764**
#82

I tried to make MysqlDriver extends from PdoDriver, and tested with no error or failure.

A lot of codes are referenced from https://github.com/joomla/joomla-platform/pull/1403, and fixed transaction bugs by using codes from OracleDriver .

### CODE REVIEW

**Comment by dongilbert** [comment]
So all the current MySQL tests pass with this? (Looks like it, since Travis is reporting green.) That's awesome. I know @ianmacl was interested in getting this done - I think it's worthwhile. IIRC @realityking had some reservations about it though. Hopefully tagging them in this comment will solicit a response from them?

**Comment by realityking** [comment]
As discussed before on Skype, reservations were handled by time ;)

**Comment by realityking** [comment]
Oh but could we get this squashed into one commit? This has commits just with style fixes and merge commits which are kinda ugly in the history.

**Comment by asika32764** [comment]
@dongilbert Yes I tested all codes through UnitTest.

@realityking Sorry but I don't know how to squashed all commits, may I need to recreate a new pull-request?

**Comment by realityking** [comment]
You can do it in place but if's the first time you're doing it, I'd make a copy of the branch first in case you make a (fatal) mistake.

You can fiend instructions here: http://davidwalsh.name/squash-commits-git

**Comment by asika32764** [comment]
OK, all commits squashed. And tests with no error.

**Comment by dongilbert** [comment]
@asika32764 Could you rebase this against master and get it able to merge again?

**Comment by asika32764** [comment]
I rebased this branch to master, but there are many other commits added in...

**Comment by dongilbert** [comment]
I'm sorry, I should have said rebased from staging. I think you can still do that, and it will all go as it should.

**Comment by asika32764** [comment]
Cleared not needed commits and rebased to staging

**Pull request merged**
