### PR TITLE
Cleanup in AbstractDaemonApplication

### PR DESCRIPTION
**Pull request by mbabker**
- Don't directly access the logger object, use `hasLogger()` and `getLogger()` instead
- Add a static container for the application for use in static methods

### CODE REVIEW

**Comment by AmyStephen** [comment]
+1 on the logger improvements. MUCH better.

Honestly, I hate to see another static added. Is there another way?

**Comment by mbabker** [comment]
Off the top of my head, not really.  We've dropped everything we had to retrieve the global application object (aside from `Factory::$application`) and without some sort of DI or anything like that floating around, not many other options at the moment.

**Comment by AmyStephen** [comment]
Is there any reason you need to provide this capability?

A DIC really isn't going to help existing static applications. Unfortunately, adding a container has not magical power, it just provides a different approach to building applications (one in which statics really have little purpose.) 

But, for legacy code, there is a lot of work implementing a IoCC/DIC. 

Step 1 is filtering out all of the code in all the classes that have to do with instances or getting data or creating other classes for the class, etc., and centralizing that logic. Then, what remains is the purpose of the class, interfaces, and better testability (plus a pile of rubbage where all the old tests were, sad.) 

Step 2 is thinking about scope and how to structure things so that you can inject only what is needed without passing half of the application through constructors.

Statics are not helped in that world, they are basically removed, which just makes me wonder why add more?

The reason I raised this question about these statics is basically to remind this team - with the framework project - the only pressure you are under is coming from you. The framework isn't carrying around an enormous community concerned about backward compatibility. You get to start over. And, you only get to do that once. But, whatever you release, you live with. You could release packages one at a time and do so in a manner that you are comfortable supporting, too. There's no hurry and this is your chance, as it were. 

I'm not trying to overemphasize this, either, this is more of a 'Go Team!' from a fan.

**Comment by mbabker** [comment]
So reading up on this some (since I haven't the slightest clue how daemon related stuff is supposed to work anyways), I went to [pcntl_signal](http://php.net/manual/en/function.pcntl-signal.php) in the PHP manual to see if there was a reason that our [daemon signal method](https://github.com/joomla/joomla-framework/blob/staging/src/Joomla/Application/AbstractDaemonApplication.php#L157) needed to be static.  It looks like as of PHP 4.3, it'll work in an object context.  So, if the method is changed to be non-static, the static var disappears, and everyone's happy.  Someone care to validate my thinking before I go making changes to the code?

**Comment by AmyStephen** [comment]
Awesome. I really don't know, @mbabker, but what you are saying makes sense
to me. I was searching for why it must be static, too. Found plenty of
static examples, but nothing that said "It must be static because...". But,
I could say the same about database connections. There are a ton of
examples of static database connections that have no real reason to be so,
but since that's what everyone has always done....

I used to love eval. Heck, I still love eval. It is a fabulous command and
I definitely understood it's danger and used it appropriately. But, it has
been so abused that I finally had to just take it off the table, so to
speak, as an option and never use it. At first, I felt limited, but after
awhile I stopped even thinking about it as a solution and apparently found
other ways.

To me, that's where statics are now. Having said that, last night, just
discovered (duh.), Closures are STATICS.

Thanks for hearing me as a supporter, not (just) a pain.

**Comment by mbabker** [comment]
Let's finish this up in #172 then :wink:

**Comment by realityking** [comment]
The changelog entry you mean is probably "The ability to use an object method as a callback became available" that doesn't mean calling from an object context but that you can specify a method on a class as the callable for the second parameter.

**Pull request merged**
