### PR TITLE
 Improved SSL (https) detection in AbstractWebApplication

### PR DESCRIPTION
**Pull request by piotr-cz**
Apparently, when behind load balancer, it terminates the SSL connection and forwards on port 80.
In effect the 
`$_SERVER['HTTPS']` header is not present anymore, but 
`$_SERVER['HTTP_X_FORWARDED_PROTO']` is with value of `'https'`.

Resources:
- Wikipedia: [Common non-standard request headers](http://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_headers) > X-Forwarded-Proto

> a de facto standard for identifying the originating protocol of an HTTP request, since a reverse proxy (load balancer) may communicate with a web server using HTTP even if the request to the reverse proxy is HTTPS
- StackOverflow: [Detecting https requests in php](http://stackoverflow.com/questions/452375/detecting-https-requests-in-php#answer-9031882)
- Wordpress: [Request: modify is_ssl() function to check for HTTP_X_FORWARDED_PROTO](http://wordpress.org/support/topic/request-modify-is_ssl-function-to-check-for-http_x_forwarded_proto)
- Random github issue: [Respect the header HTTP_X_FORWARDED_PROTO](https://github.com/puma/puma/pull/200)

Quick and dirty worakound to set HTTPS header manually in `.htaccess`:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{HTTP:X-FORWARDED-PROTO} ^https$
    RewriteCond %{HTTP:X-SSL-CIPHER} !^$
    RewriteRule ^(.*)$ - [E=HTTPS:on]
</IfModule>
```

### CODE REVIEW

**Comment by dongilbert** [comment]
On the WordPress ticket, @webaware made a good point:

"NB: note that it isn't safe to assume that these headers are added by the host; because they are non-standard headers, they can be added by the client, and thus some crafty prick could manufacture a situation where the request to the server tells it that SSL is enabled when it isn't, and perform a man-in-the-middle attack. I therefore recommend that core does not accept the patch on this ticket, and instead this function be handled by a plugin."

That said, I'm not against accepting this into core, but I think we need to research it a bit more, and maybe add a config option to enable it (leaving it disabled by default)?

**Comment by eddieajau** [comment]
Should we break the SSL check out into something like `protected function detectSSL` and then this method can be overridden by the application with a standard snippet? In other words, we don't actually put the new check into this class, but simply move the check to a class method so the application can do it.

**Comment by piotr-cz** [comment]
I didn't think about that, indeed you could probably just send this header from the client.

Along with the `X_FORWARDED_PROTO` header there is another one sent: `HTTP_X_SSL_CIPHER` with with [certificate description](http://www.openssl.org/docs/ssl/SSL_CIPHER_get_name.html) like `RC4-SHA                 SSLv3 Kx=RSA      Au=RSA  Enc=RC4(128)  Mac=SHA1` but I this doesn't help at all ([possible values](https://we.riseup.net/debian/ssl-cyphers#working-ciphers)).

Summarized, probably only secure fix is to specify the `site_uri` manually in app configuration (it's just pain when moving application between servers):

`config.json`

``` JSON
"site_uri": "https://mywebsite.com"
```

Resources: 
- Zend Framework 2: [ZF-5012: Checks for SSL should include HTTP_X_FORWARDED_PROTO as well as HTTPS](http://framework.zend.com/issues/browse/ZF-5012)
- [WordPress is_ssl() doesn’t work behind some load balancers](http://snippets.webaware.com.au/snippets
  /wordpress-is_ssl-doesnt-work-behind-some-load-balancers/)
- YII is [using similar check](https://github.com/yiisoft/yii/blob/master/framework/web/CHttpRequest.php#L538), at least we are not alone here.

**Comment by piotr-cz** [comment]
If nobody has any idea how to get around that, I'll close the issue then.

**Comment by piotr-cz** [comment]
@eddieajau 
Actually there's already a method [`isSSLConnection`](https://github.com/joomla/joomla-framework/blob/staging/src/Joomla/Application/AbstractWebApplication.php#L639), just it's not being used by the aforementioned [`detectRequestUri`](https://github.com/joomla/joomla-framework/blob/staging/src/Joomla/Application/AbstractWebApplication.php#L571).

**Pull request closed without merging**
