### PR TITLE
Optimize DatabaseDriver::replacePrefix()

### PR DESCRIPTION
**Pull request by mbabker**
As accepted in the CMS at joomla/joomla-cms@d158e5be074195600b965c21e0794130d9b7fd9c

### CODE REVIEW

**Comment by eddieajau** [comment]
I'd like to see a performance test on this one, and the unit test needs to be expanded to make sure we haven't broken anything (I'll see if I can find some time to do this).

**Comment by mbabker** [comment]
As a start, I added a couple of test cases basically changing the number of underscores in each case.  Those passed locally.

**Comment by mbabker** [comment]
I think we've got test cases now covering the logical uses, just need someone to do some kind of performance test.

**Comment by eddieajau** [comment]
Unless I've stuffed up, preg wins by a big margin (but in real terms we are probably only talking a difference of 1 ms per page load - it's probably insignificant compared to optimising even one of those huge queries).

https://gist.github.com/eddieajau/e060f378b5da3d2a4cf9

```
50 queries tested 1000 each
byPreg:0.402 seconds
byLexer:1.218 seconds
```

But if those figures are right, why not.

**Comment by mbabker** [comment]
I'd hold of on this for the moment.  The preg that's in place now is causing some issues in select CMS environments (most reports are on a Debian based OS), but the one that's commented in that long block seems to be working for all cases.  I'll update when we have that answered in the next day or so.

**Comment by ghost** [comment]
I broke my github repo so I can't access it to create a patch.  Where it breaks it is breaking 'correctly' in that the use of the lookbehind regular expression assertion is supposed to fail if there are no chars to check.

echo $db->replacePrefix('#__something_items'));
doesn't work
echo $db->replacePrefix(' #__something_items'));
Works.

The $db->quoteName method is merely adding a charector in front of the table name - it doesn't matter WHAT you put there as long as something is there.

The problem is the use of the look behind:
http://php.net/manual/en/regexp.reference.assertions.php
The implementation of lookbehind assertions is, for each alternative, to temporarily move the current position back by the fixed width and then try to match. If there are insufficient characters before the current position, the match is deemed to fail. 

Ugly hack to JDatabaseDriver replacePrefix to fix this:

$prePadSql = false;
// Look behind assertion requires at least one leading char
$firstPrefix = strpos($sql, $prefix);
if ($firstPrefix===0)
{
$prePadSql = true;
$sql = ' '.$sql;
}
// If there is no prefix, give up
if (!strpos($sql, $prefix))
{
return $sql;
}

/*
- Pattern is: find any non-quoted (which is not including single or double quotes) string being the prefix
- in $sql possibly followed by a double or single quoted one:
-   (
- not including quotes:
- positive lookahead: (?=
- not including " or ': [^"\']+
- )
- including exactly the prefix to replace: preg_quote( $prefix, '/' )
-  )(
- Followed by a double-quoted: "(?:[^\"]|\.)*"
- Or: |
- single-quoted: \'(?:[^\\']|\.)*\'
-  )
- possibly: ?
- $pattern = '/((?=[^"\']+)' . preg_quote($prefix, '/') . ')("(?:[^\"]|\.)_"|\'(?:[^\\']|\.)_\')?/';
  _/
  $pattern = '/(?<=[^"\'])(' . preg_quote($prefix, '/') . ')("(?:[^\\"]|.)_"|\'(?:[^\\\']|.)*\')?/';

$sql= preg_replace($pattern, $this->getPrefix() . '\2', $sql);

// remove padding from sql
if ($prePadSql)
{
$sql = substr($sql,1);
}
return $sql;

**Comment by eddieajau** [comment]
Closing until we get a green light to merge.

**Pull request closed without merging**
