### PR TITLE
Update AbstractController.php

### PR DESCRIPTION
**Pull request by moolah-ecommerce**
If an abstract class is meant to be derived, we should at least provide access to the stuff they need.  Outside, accessor methods are public for general use.

### CODE REVIEW

**Comment by mbabker** [comment]
There are get/set methods for those two objects in the abstract class already.  What's the issue you're having here?

**Comment by dongilbert** [comment]
I do prefer `$this->app` to `$this->getApplication()`

**Comment by eddieajau** [comment]
I actually think we need to discuss whether the base Controller class should be coupled to the application and the input.

**Comment by moolah-ecommerce** [comment]
This is an abstract class which, by definition, needs to be inherited.  It may be a best practice to require the API call, but I think its safe to assume that the derived class understands specific use cases better than the generic framework.

If the derived can't access basic vars, then what is the point of this class?  

Regarding coupling, yes in theory, but if I really want to do $kung->foo() then I'll just use symfony.

-Toby

**Comment by eddieajau** [comment]
We do indeed aim for best practice. The private variables are used so that
when the application is set through `setApplication` there is a type hint
to ensure you can't shove, for example, a scalar in there by accident. Same
goes for the Input. You could argue that a magic __get might be justified
but I go back to my earlier comment that we actually need to review whether
the coupling of the application is appropriate (this controller class
predates the DI work, so that might have a new influence on how it should
be designed). I think we need to at least take them out of the interface.
Even the execute method has caused some level of debate (single use vs
multiple use controllers, and I'm starting to wonder if we should just
allow both).

With reference to your comment about Symfony, using methods over properties
has nothing to do with coupling. Even were we to accept your PR, the question
of coupling to our Application and Input classes remains in my mind. To
that end though, I think you'll find our new controller much lighter than
Symfony's or the CMS's counterparts.

**Comment by dongilbert** [comment]
We'll stick with the access methods instead and look at refactoring for v2.

**Pull request closed without merging**
