### PR TITLE
More improvements for the Uri package.

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by dongilbert** [comment]
While we're improving, could you fix the namespacing on the Exceptions here: https://github.com/realityking/joomla-framework/blob/06c042ee8f133f5b25cc67d29a21297db178576d/src/Joomla/Uri/UriImmuteable.php#L38

Also, reading an if statement should be clear what it does, "if true is equal to param" makes programatic sense, but not grammatic sense. You would say "if param is equal to true". I know this has become a popular syntax style recently, but it's not very readable, IMO. https://github.com/realityking/joomla-framework/blob/06c042ee8f133f5b25cc67d29a21297db178576d/src/Joomla/Uri/UriImmuteable.php#L50

**Comment by florianv** [comment]
Just a few things :
- I think it should be Immutable without the "e" : http://en.wikipedia.org/wiki/Immutable_object
- Also I would prefix it instead of suffix `ImmutableUri` in term of conventions
- The class https://github.com/joomla/joomla-framework/blob/staging/src/Joomla/Uri/UriImmuteable.php#L34 is final so all methods are implicitely final, public function __set would be clearer IMO.

Do we assume that people is tricky enough to call the constructor on an already created object :D ?

Otherwise, +1

**Comment by dongilbert** [comment]
- I can't believe I didn't catch that - :facepalm:
- In PHP 5.5, there is a new DateTimeImmutable class, so we were going with that pattern.
- I agree, since the class is final, we don't need to have `final` on the methods.

**Comment by florianv** [comment]
ah ok, didn't see it. Habitually I look here https://wiki.php.net/rfc, but I'm not able to find the link for the feature, do you have one please ? Would be interesting to see if the constructor throws an exception.

**Comment by florianv** [comment]
Found it finally. Looks like the constructor doesn't throw an exception when calling it an other time

https://github.com/php/php-src/blob/php-5.5.0alpha4/ext/date/php_date.c#L2599

**Comment by realityking** [comment]
Thanks for the feedback Florian.
- You're right, will fix that. Did I mention my spelling sucks?
- See Don's explanation
- Will fix that too.

As for your last point, I think it's better to be save than sorry so I thought it to be better to prevent that possibility.

**Comment by florianv** [comment]
np @realityking. 
Spelling issues happen sometimes.
Yes, you are right it can lead to really unexpected stuff.

**Pull request merged**
