### PR TITLE
Add a global with() method.

### PR DESCRIPTION
**Pull request by elkuku**
Given the positive feedback on #180, here is a proposal to add a global function.
Uhhh what ? (wtf).... No, please keep on reading ;)

**Benefits**
- Reduce the usage of **local variables**.
- Add **forward compatibility** for the PHP 5.4 feature [Class member access on instantiation](http://php.net/manual/en/migration54.new-features.php).

**Example**:
Plain PHP 5.3:

``` php
$class = new Class;
$result = $class->method();
```

Using the proposed `with()` function:

``` php
$result = with(new Class)->method();
```

Now when switching the minimum requirements to PHP 5.4 you simply change it to:

``` php
$result = (new Class)->method();
```

and remove the whole evil global function from the code base...

I hope, you can see the benefits.

The method will be added to a global file in `src/Joomla/PHP/methods.php` which will be loaded by Composers [files autoload mechanism](http://getcomposer.org/doc/04-schema.md#autoload).

---

**Disclaimer**
This has been stolen from the Laravel framework and I am posting the whole magical function here, hoping that they won't prosecute me for copyright infringement ;)
From [laravel/framework/blob/master/src/Illuminate/Support/helpers.php#L869](https://github.com/laravel/framework/blob/master/src/Illuminate/Support/helpers.php#L944)

``` php
function with($object)
{
    return $object;
}
```

The power of simplicity :)

### CODE REVIEW

**Comment by piotr-cz** [comment]
Idea is very slick, but are there really many use cases?
Won't we lose some readability (usually constructor takes parameters)?

``` PHP
// Creating a Class
$class = new Class($param1, $param2);

// Make it do something
$result = $class->method();


// Creating a class and making it do something
$result = with(new Class($param1, $params))->method();
```

**Comment by elkuku** [comment]
> ...are there really many use cases?

Seems so, since it has been accepted as a feature for PHP 5.4 ;)

As for the readability: I think it's something like the usage of name spaces (uh, that looks like a windoze path :P) or chaining.
You'll get used to it with the time...

You may also use line breaks:

``` php
$result = with(new Class($param1, $param2))
   ->method();
```

After the removal, in PHP 5.4, that wouldn't look that bad:

``` php
$result = (new Class($param1, $param2))
   ->method();
```

Does that make it better - or worse ? :wink:

**Comment by elkuku** [comment]
Oh and I forgot - there are some use cases "almost" real world:
[https://github.com/joomla/jissues/blob/framework/cli/CliApp/Application/CliApplication.php#L192](https://github.com/joomla/jissues/blob/framework/cli/CliApp/Application/CliApplication.php#L192)

``` php
try
{
   with(new $className($this))->execute();
}
```

https://github.com/joomla/jissues/blob/framework/cli/CliApp/Command/Get/Issues.php#L204

``` php
$table->opened_date = with(new Date($issue->created_at))->format('Y-m-d H:i:s');
```

https://github.com/joomla/jissues/blob/framework/cli/CliApp/Command/Get/Get.php#L124

``` php
$projects = with(new ProjectsModel(Container::getInstance()->get('db')))->getItems();
```

using, of course, our own `with()` method :wink:

**Comment by piotr-cz** [comment]
Thaks, now the benefit is clear to me.

**Comment by dongilbert** [comment]
Do you think we should credit @taylorotwell in any way maybe within the docblock for the function? Other than that question, I think this is good to merge.

**Comment by taylorotwell** [comment]
Don't worry about it. :smile:

**Pull request merged**
