### PR TITLE
Added hhvm php version for unit testing

### PR DESCRIPTION
**Pull request by ghost**
Modified .travis.yml to include Facebook Hiphop hvm version of PHP for unit testing.   Expecting the tests to fail, but having them done will provide a basis for correction

### CODE REVIEW

**Comment by ghost** [comment]
I'm working on resolving some issues for testing so don't merge yet. :-)

**Comment by ghost** [comment]
Closing this pull request and will open others.  Found a large number of bugs in the unit tests themselves[incorrect checks on memcached, mysqli to skip tests when not there, etc]

**Comment by dongilbert** [comment]
Yeah, I've had some issues getting it working correctly as well. Right now, I'm trying to get it re-installed on my current system.

**Comment by ghost** [comment]
Replaced with #335 for partial implementation. Fixes will require separate pull requests/

**Pull request closed without merging**
