### PR TITLE
Make ArrayHelperTest resilient against undefined sort order

### PR DESCRIPTION
**Pull request by elgenie**
The documentation of usort (http://us1.php.net/manual/en/function.usort.php)
makes it clear that "If two members compare as equal, their relative order in the sorted array is undefined."

This pull request makes the test work on hhvm as well as Zend implementations.

### CODE REVIEW

**Comment by eddieajau** [comment]
Travis is reporting a test failure:

```
There was 1 failure:
1) JRegistryFormatXMLTest::testObjectToString
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '<?xml version="1.0"?>
-<registry><node name="foo" type="string">bar</node><node name="quoted" type="string">"stringwithquotes"</node><node name="booleantrue" type="boolean">1</node><node name="booleanfalse" type="boolean"></node><node name="numericint" type="integer">42</node><node name="numericfloat" type="double">3.1415</node><node name="section" type="object"><node name="key" type="string">value</node></node><node name="array" type="array"><node name="nestedarray" type="array"><node name="test1" type="string">value1</node></node></node></registry>
+<registry><node name="foo" type="string">bar</node><node name="quoted" type="string">"stringwithquotes"</node><node name="booleantrue" type="boolean">1</node><node name="booleanfalse" type="boolean"/><node name="numericint" type="integer">42</node><node name="numericfloat" type="double">3.1415</node><node name="section" type="object"><node name="key" type="string">value</node></node><node name="array" type="array"><node name="nestedarray" type="array"><node name="test1" type="string">value1</node></node></node></registry>
 '
/home/travis/build/joomla/joomla-framework/src/Joomla/Registry/Tests/format/FormatXmlTest.php:59
```

Are you getting this running tests locally?

**Comment by dongilbert** [comment]
Thats a common problem, Andrew. It should have been fixed by a recent PR.

**Comment by eddieajau** [comment]
Still failing.

https://travis-ci.org/joomla/joomla-framework/jobs/14373307

**Comment by elkuku** [comment]
Branch should be updated - test is 10 days old ;)

**Comment by dongilbert** [comment]
Closed by #314

**Pull request closed without merging**
