### PR TITLE
Add colors to CLI applications

### PR DESCRIPTION
**Pull request by elkuku**
This will add the possibility to use colors in CLI applications.

**Disclaimer**: This has been inspired by reading the documentation of [symfony/console](http://symfony.com/doc/master/components/console/introduction.html) which has been copied almost verbatim to our [readme.md](https://github.com/elkuku/joomla-framework/blob/cli-application/src/Joomla/Application/README.md), included here for reference:
The code, however, is mine ;)
## Colors for CLI Applications

It is possible to use colors on an ANSI enabled terminal.

``` php
// Green text
$this->out('<info>foo</info>');

// Yellow text
$this->out('<comment>foo</comment>');

// Black text on a cyan background
$this->out('<question>foo</question>');

// White text on a red background
$this->out('<error>foo</error>');
```

You can also create your own styles.

``` php
use Joomla\Application\Cli\Colorstyle;

$style = new Colorstyle('yellow', 'red', array('bold', 'blink'));
$this->getOutput()->addStyle('fire', $style);
$this->out('<fire>foo</fire>');

```

Available foreground and background colors are: black, red, green, yellow, blue, magenta, cyan and white.

And available options are: bold, underscore, blink and reverse.

You can also set these colors and options inside the tagname:

``` php
// Green text
$this->out('<fg=green>foo</fg=green>');

// Black text on a cyan background
$this->out('<fg=black;bg=cyan>foo</fg=black;bg=cyan>');

// Bold text on a yellow background
$this->out('<bg=yellow;options=bold>foo</bg=yellow;options=bold>');
```

### CODE REVIEW

**Comment by dongilbert** [comment]
I think it would be worthwhile to somehow make these accessible maybe via `__call()` or something similar, as it's  much easier to right `$this->fire('foo')` or even `$this->outFire('foo')` than to write out the explicit tags, imo.

**Comment by elkuku** [comment]
Well, I wrote several CLI scripts in the past, trying to colorize them, and every approach I took felt somewhat clumsy. Symphony's way using HTML style "tags" is pretty cool IMHO (like most of the stuff they produce).

Think of longer Text that includes several colorized parts.

**Comment by dongilbert** [comment]
I agree longer text would be using just the out() method. Maybe it's
something I just need to get over. :)

**Comment by elkuku** [comment]
gimme five :hand:

**Comment by dongilbert** [comment]
I pulled and tested it and like it a lot. :hand:

**Pull request merged**
