### PR TITLE
Remove requires from tests/core/case/database.php

### PR DESCRIPTION
**Pull request by asika32764**
When I run UnitTest, it returns error:

```
Warning: require_once(PHPUnit/Extensions/Database/TestCase.php): failed to open stream: No such file or directory in ***\tests\core\case\database.php on line 9

Fatal error: require_once(): Failed opening required 'PHPUnit/Extensions/Database/TestCase.php' (include_path='.;***\php\PEAR') in ***\tests\core\case\database.php on line 9
```

So I remove requires from this file, then it working fine.

### CODE REVIEW

**Comment by dongilbert** [comment]
Do you have [DbUnit](https://github.com/sebastianbergmann/dbunit) installed? It's required for our database tests, and probably why the require failed. I do agree with you though, we shouldn't have the hardcoded require, and instead depend on autoloading.

**Comment by asika32764** [comment]
I'm not sure whether am I installed Dbunit or not, I just use whole phpunit.phar to test it.

I'm now using this phpunit.phar to test `DatabaseDriver` and `'MysqlDriver`, and it's working fine. I guess that Dbunit has already included in my phpunit.phar file.

**Comment by dongilbert** [comment]
Yeah, that makes sense. I'll have to pull the code locally and test before merging, but I think it's good, since Travis isn't complaining.

Thanks.

**Comment by dongilbert** [comment]
Confirmed, removing the hardcoded `require` block doesn't break the existing tests, so good to merge. Thanks!

**Pull request merged**
