### PR TITLE
Updated Readme's for JTwitter and JFacebook

### PR DESCRIPTION
**Pull request by babsgosgens**
I believe these are the correct instructions for JTwitter and JFacebook. Regards, Babs

### CODE REVIEW

**Comment by dongilbert** [comment]
Classes are namespaced in the Framework, and don't have the explicit `J` prefix anymore. 

`JFacebook` becomes `Joomla\Facebook\Facebook`
`JFacebookOauth` becomes `Joomla\Facebook\Oauth`

**Comment by dongilbert** [comment]
Thanks for the effort though! It's good to see interest here. :)

**Comment by babsgosgens** [comment]
Hi Don,

The thing is, if I try to instantiate like so: new OAuth($options)
the framework will throw an error: Class 'Joomla\Facebook\OAuth' not found

If I call the Facebook version however, all is well in J! City. Same for the other two instances.

And yes, glad to see the inclusion of these new social libraries. Onwards to include Flickr, Dribbble and the likes ;)

**Comment by HermanPeeren** [comment]
Hi Babs,

Do you have: use Joomla\Facebook\OAuth
on top of the code where you instantiate OAuth?

**Comment by babsgosgens** [comment]
Yes, correct:

use Joomla\Facebook\Facebook;
use Joomla\Facebook\OAuth;
use Joomla\Registry\Registry;

**Comment by eddieajau** [comment]
Hi Babs. The "J" prefix is the problem. We don't use that in the Framework.

**Comment by babsgosgens** [comment]
Hi Andrew,

I understand that. Consider this code:

use Joomla\Registry\Registry;

new Registry; // Class 'Joomla\Registry\Registry' not found
new JRegistry; // No error

What am I missing?

Thanks, Babs

**Comment by HermanPeeren** [comment]
Are you working in Joomla! CMS 3.x? That doesn't have the (namespaced) Joomla! Framework on board! There you don't use the "use"-clause, but instantiate JRegistry, JFacebook and JFacebookOauth. Actual API can be found at http://asika32764.github.io/Joomla-CMS-API-Document/ . A new API-document is in the make for the upcoming Joomla! CMS 3.2.

**Comment by babsgosgens** [comment]
Am using 3.1.5. That explains it then, thanks Herman :)

**Comment by HermanPeeren** [comment]
Yep, see my updated comment: in Joomla CMS 3.1.5 you don't use the "use"-clause, but instantiate JRegistry, JFacebook and JFacebookOauth. Actual API can be found at http://asika32764.github.io/Joomla-CMS-API-Document/ . A new API-document is in the make for the upcoming Joomla! CMS 3.2.

**Comment by eddieajau** [comment]
Ah, ok. Yes, you are right if you are using the CMS. The confusion is that this is the documentation for the Framework and your changes won't actually work. Do you understand the difference?

**Comment by babsgosgens** [comment]
Yes, I didn't realize they were two different versions. It does explain why the readme was missing in my installation, I was wondering about that ;)

**Comment by HermanPeeren** [comment]
It is a bit confusing, especially because the word "framework" has been used before in Joomla. Some years ago we had the CMS with a Framework on board. The CMS was built on top of that framework and very much integrated with it. That framework was splitted of and worked on as a separate project: the Joomla Platform. That was the old framework, but separated from the CMS. It was used as "framework" in the CMS. Then a new project was started: to namespace the Platform and to get small packages available on Packager/Composer. That initiative was called... the Joomla Framework. That is where we are now. In the meantime the Platform was "merged back" to the CMS.  The current Framework is not used in the current CMS.

**Pull request closed without merging**
