### PR TITLE
Don't (un)serialize the db property. Closes #137 and fixes joomla/joomla-platform#1167

### PR DESCRIPTION
**Pull request by dongilbert**

### CODE REVIEW

**Comment by eddieajau** [comment]
Do we need a unit test change to cover this?

**Comment by dongilbert** [comment]
We should add something in to check to make sure it doesn't get changed accidentally in the future, but the current tests pass just fine as is. I'll work on that later.

**Comment by dongilbert** [comment]
Unit tests added. They fail without the fix, and pass with it. :+1:

**Comment by dongilbert** [comment]
@elinw https://github.com/joomla/joomla-cms/pull/1040

**Comment by elinw** [comment]
Thanks we actually already committed since we were buidling packages.

http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=30652

see the don diff :P

**Pull request merged**
