### PR TITLE
B/C breaking change in unpack() for PHP 5.5

### PR DESCRIPTION
**Pull request by mbabker**

### CODE REVIEW

**Comment by mbabker** [comment]
So I finally dug into why we're getting failures with the apt-get piece on Travis.  It's looking for http://security.ubuntu.com/ubuntu/pool/main/a/apache2/apache2.2-bin_2.2.22-1ubuntu1.3_amd64.deb (1.3) but http://security.ubuntu.com/ubuntu/pool/main/a/apache2/apache2.2-bin_2.2.22-1ubuntu1.4_amd64.deb (1.4) is what's on the server.

**Comment by dongilbert** [comment]
Is there any way to force it to use the right one?

**Comment by mbabker** [comment]
You know a way to hi-jack apt-get to point to specific files/locations?

**Comment by dongilbert** [comment]
I don't, but I think there's a way to directly install specific .deb's, maybe not through apt-get. @betweenbrain might know?
—

**Comment by betweenbrain** [comment]
WARNING: Untested. You might want to test on a vagrant or vm first.

Looks like `sudo dpkg -i --force-depends http://security.ubuntu.com/ubuntu/pool/main/a/apache2/apache2.2-bin_2.2.22-1ubuntu1.3_amd64.deb` would do the trick. But, that deb now seems to be located at https://launchpad.net/~ubuntu-security/+archive/ppa/+build/4355409/+files/apache2.2-bin_2.2.22-1ubuntu1.3_amd64.deb as 1.4 is the current version.

From http://manpages.ubuntu.com/manpages/lucid/man1/dpkg.1.html regarding `--force-`

```
         Warning: These options are mostly intended to be used  by
         experts  only.  Using  them  without  fully understanding
         their effects may break your whole system.
```

**Comment by ianmacl** [comment]
I assume somebody has tried adding a sudo apt-get update before the install?

**Comment by dongilbert** [comment]
I don't think so, but apt-get is trying to grab the wrong deb, so I'm not sure that would help. But I defer on this one, I haven't had to do linux administration for a while.

**Pull request merged**
