### PR TITLE
Refactor Router to allow abitrary callables and remove dependency on Controller and Input

### PR DESCRIPTION
**Pull request by dongilbert**
This PR implements a simplified Router class that does not depend on our Input or Controller classes to function. 

The changed functionality is as such:
- Remove `RestRouter` since it's tied to a single-action controller method
- Remove `fetchController`, `setDefaultController` and family
- Use `parseRoute($route)` instead of `getController($route)`
- Returned value is no longer an instance of the controller class, but rather an array structured as:

``` php
$returnedArray = [
    'controller' => 'nameOfControllerOrCallableOrClosureInstance',
    'vars' => [
        // vars extracted from route, including `_rawRoute`
    ]
];
```

This greatly decouples the `Router` class, and makes it a standalone routing package, that is not tied to any implementation, and it's more flexible. It leaves the actual instantiation and variable setting to the calling code, which allows for more flexible implementations.

What do you think? I'm not sure this is ready yet, but would like to start the discussion with some code.

### CODE REVIEW

**Comment by dongilbert** [comment]
One thing to possibly add to this is the ability to set a `Class@method` type syntax, and then parsing that and adding an `action => $method` key to the returned array. It would only apply when you add the controller with the `@` as the separator. If you use `::`, then it should just be set as the controller parameter (don't add an action key) to be treated as a static `controller::method` call (if used with `call_user_func`). 

I'm trying to think of something that would be clear and concise, and not get confused with the different syntax for various callables. http://www.php.net/manual/en/language.types.callable.php

**Comment by dongilbert** [comment]
Another thing to consider is the ability to set specific regex patterns for each named variable. Something like:

``` php
$router->addMap(
    '/:name/:id',
    'Controller@action',
    array(
        'name' => '([a-z]+)',
        'id' => '(\d+)'
    )
);
```

**Comment by asika32764** [comment]
I'm waiting this feature for a long time. Hope this PR merged soon.

:+1:

**Comment by asika32764** [comment]
So if I want to addMap with a controller with namespace, The code will like this?

``` php
$router->addMap(
    '/:name/:id',
    'Foo\\Bar\\Controller\\List\\State\\UpdateController@execute',
    array(
        'name' => '([a-z]+)',
        'id' => '(\d+)'
    )
);
```

---

An inspiration, not sure is it a good idea or not. Could we add keys for every Route? Like this:

``` php
$router->addMap('item_edit', '/edit/:id', ...);
```

That support quickly build route:

``` php
<a href="<?php echo $this->route->build('item_edit', array('id' => $id))?>" >Link</a>
```

**Comment by dongilbert** [comment]
So what about routing to REST resources, treating a class as a single point of reference for an entity. Something like:

``` php
class UserController
{
    public function getAction(//...)
    public function postAction(//...)
    public function putAction(//...)
    public function deleteAction(//...)
}

$router->addResource('/users', 'UserController');
```

**Comment by dongilbert** [comment]
Will PR against Router repo directly.

**Pull request closed without merging**
