### PR TITLE
Refactor Registry to use Dependency Injection.

### PR DESCRIPTION
**Pull request by realityking**
This pull request also contains factories for Registry and Keychain to keep this useable until we have some sort of DIC.

### CODE REVIEW

**Comment by realityking** [comment]
The travis failure is due to the OAuth issue. Test on 5.3 was successful.

**Comment by AmyStephen** [comment]
Good work on "fixing" the injecting of dependencies.

I would change RegistryFactory getRegistry. https://github.com/realityking/joomla-framework/blob/1e348f23b00e890ae8d017877949f1861b253b5d/src/Joomla/Registry/RegistryFactory.php

I would get rid of all statics, anywhere. If those are considered needed to provide "global" memory, not a problem, there are other ways (containers for example) that can get that result in better ways. So, as long as you guys are going to this trouble, I'd get rid of those. Otherwise, it will turn people off who would be very good to involve. 

Then, I would redesign the architecture a bit so that the factory only created one format per RegistryFactory getRegistry request. 

So, been poking around with it and I realize, what that would likely lead to is the removal of RegistryFactory. I can't justify it in my mind. Seems like it's a class to instantiate the class you want constructed. 

I think maybe it's a hack because of the static - since if you wanted another format, the static would create a problem for your first format. Get rid of the static and you don't need the hack. Or, the class. 

Am I right on this? Or, did I really miss the point?

**Comment by dongilbert** [comment]
It's an intermediary class since we don't have a container right now to handle it. That will come later but at the moment what's in place is useful. Remember, v1.0 is not the vast architectural restructuring that we want it to be.

**Comment by realityking** [comment]
Hi Amy,

you got that completely right. These two Factories are just a temporary solution until we've figured what kind of DIC (or whatever else) we want to use. My plan is not to have it present in any final release but it just would be too hard to work with if we've had to set up the entire thing manually every time.

**Comment by AmyStephen** [comment]
@dongilbert I do understand you aren't trying to get rid of statics, but I see new ones coming in now and so, I guess I'm challenging the team to adopt a "just say no!" approach to more, at least.

@realityking I appreciate the point. My guess is most devs who work with packages have class construction approaches and they just fit new classes into that strategy. (Not certain, though, it'd be good to understand for sure.) Personally, I wouldn't do it, mainly because I wouldn't want to add code that I already knew I would be deprecating ASAP. 

Fair, not fair, like it, don't like it, the truth is, those statics will stand in the way of adoption. I'd set the bar high for new ones. My 2 cents. ;-)

**Comment by dongilbert** [comment]
"redesign the architecture a bit so that the factory only created one format per"

After thinking about it a bit, I wonder if we should go down this road. Instead of registering a list of supported formats, we should just use a required constructor argument which would allow us to drop the factory altogether.

`public function __construct($data, $format = 'json')`

I know we currently can pass in the `$data` when creating a `new Registry($data)` instance, but in that case I feel like you should already know the format of the data you are passing in, right? So it would be trivial to do this instead `$reg = new Registry($yamlString, 'yaml')`. Then, the constructor would do a bit of work and register the passed format. If you wanted to use an alternative parser, you would have to create the registry object, register your custom parser, and then `bindData`.

There's a bit more too it than that. The constructor would actually be doing quite a bit of heavy lifting to load the formatter and get the object from the input data, but I think it would be doable. What do you guys (in the general usage of the term) think about that?

**Comment by ghost** [comment]
I think it's better to separate the formatter out altogether and let
register be what it is - a registry.  Let the formatter be instantiated
separately so it only has one job which is formatting.  Most of the places
where we use registry in the framework has no need at all for formatting.

**Comment by dongilbert** [comment]
So really it would just be dropping the factory altogether. Go one format per instance (or multiple if you need it, useful for swapping an input format to a different output format) which you have to explicitly add. No magic, and it allows you to specify your formatters. I'm fine with that. Should we add a `loadDefaultFormats()` method that will bring in our formatters?

**Comment by ghost** [comment]
Mmm...  I was thinking more:
$registry = new Registry;
$registry ...

$formatter = new Registry\Formatter\XmlFormatter;
$result = $formatter->format($registry);

I think we already made registry implement array access so the formatter
can just iterate through and format the data as needed.

Ian

**Comment by dongilbert** [comment]
That's a good separation of concerns and single responsiblity principle going on right there.

**Comment by realityking** [comment]
@dongilbert 
The data you can pass into the constructor with the code in this pull request would be arrays and objects - no serialized data. The code currently in the repository also supports JSON strings but that meant we'd have to have a hard dependency on FormatJson and that's not something I want to have. I see that fact that you can load anything trough the constructor just as a helpful shortcut. I actually think it'd be more clean to not accept any data in the constructor.

@ianmacl-api-test 
That's probably the best approach, though it means we'de have to open up our internal data store. Do we wanna do that?

**Comment by AmyStephen** [comment]
Love where this is going. 

Wonder, maybe even take it one half a step further and use an adapter pattern? Handler for each format (which you have), instantiate the formatter injecting the data via the constructor, then inject the formatter instance with an Interface type into the registry via the constructor.

That would clean up the YAML include checking and only create the JSON dependency on the JSON formatter.

``` php
    $formatter = new Registry\Formatter\XmlFormatter ($data); 
    $registry = new Registry\Registry(Interface $formatter); 
    $result = $registry->get('id', 0);
```

Then, when you settle on your DI approach you could even create a facade effect of sorts and bury the complexity of constructing both classes.

**Comment by AmyStephen** [comment]
Looking back at @dongilbert 's example - I agree with your signature and instantiating the format in that manner. 

The benefit of keeping that generic client-facing class is to uncouple the application from the format option. That way, a switch from JSON to Yaml, for example, would not require application changes. 

So, kind of combining both Ian's and yours results in an adapter approach, which ends up solving the last point @realityking is making about opening up the internal data store.

I think it's a good fit for an adapter. Hope I didn't misunderstand.

**Comment by dongilbert** [comment]
FWIW - I really like the idea of a localized Factory / Builder / Service Provider for each of our separate components. This PR is a step in the right direction, IMO. Can you make this mergeable again so we can get it in?

**Comment by realityking** [comment]
I'll look into it.

**Comment by asika32764** [comment]
I have a little question, if we create a new instance and immediately inject all formatter without lazyloading, like Symfony style:

``` php
$instance = new Registry;
$instance->registerFormat(new IniFormat);
$instance->registerFormat(new JsonFormat);
$instance->registerFormat(new PhpFormat);
$instance->registerFormat(new XmlFormat);

if (class_exists('Symfony\Component\Yaml\Parser') && class_exists('Symfony\Component\Yaml\Dumper'))
{
    $instance->registerFormat(new YamlFormat(new YamlParser, new YamlDumper));
}
```

OR

``` php
$instance = new Something(array(
    new SubClassA,
    new SubClassB,
    new SubClassC,
    new SubClassD,
));
```

Is this good to performance?  I'm just curious about that.

Or if the SubClass is singleton, is this good to use DI Container in Factory?

``` php
$instance = new Something(array(
    $container->get('something.subclassA'),
    $container->get('something.subclassB'),
    $container->get('something.subclassC'),
    $container->get('something.subclassD')
));
```

Thanks.

**Comment by dongilbert** [comment]
It only does that if you use the AbstractFactory approach, which we provided for. You could create the new Registry and add the Formats individually. The other is really just a convenience method. I don't think it would have too much impact on performance. 

—

**Comment by asika32764** [comment]
I'm understand. Thanks Don.

**Comment by dongilbert** [comment]
I have a PR in to Rouven to make this mergeable again. Then we can add a `RegistryServiceProvider` and a `KeychainServiceProvider`, and call this good. :+1:

**Pull request closed without merging**
