### PR TITLE
Add backtrace information to database debug log

### PR DESCRIPTION
**Pull request by elkuku**
This will pass  the backtrace information to any attached logger when executing a database query in debug mode.

Currently implemented for `Mysql`, `Mysqli`, "`Pdo`", `PostgreSql`, and `SqlSrv` drivers.

An example implementation might render like this:

issues list 2013-10-03 13-36-10

### CODE REVIEW

**Comment by eddieajau** [comment]
:+1:

**Comment by dongilbert** [comment]
Is there a reason to not add it to the others? Oh yeah, and :+1:

**Comment by elkuku** [comment]
Actually I only modified the drivers I was able to test, but functionality should be the same so I went ahead and changed the other ones too.

**Comment by realityking** [comment]
Is it just me or is the driver the wrong place to do these things?

**Pull request merged**
