### PR TITLE
Change required PHP version from 5.3.10 to 5.3.1 (typo?)

### PR DESCRIPTION
**Pull request by eirslett**
I suspect this is a typo in composer.json?

### CODE REVIEW

**Comment by mbabker** [comment]
This is not a typo.  Our intention is to raise the minimum supported version of PHP to 5.3.10 with this updated code in order to better use the PHP API in addition to the numerous security and bug fixes that it brings.

**Comment by eirslett** [comment]
There is a problem though - package managers aren't up to date on PHP versions. If you run apt-get install php5, this is what you get:

PHP 5.3.3-7+squeeze14 with Suhosin-Patch (cli) (built: Aug  6 2012 14:18:06)
Copyright (c) 1997-2009 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with Suhosin v0.9.32.1, Copyright (c) 2007-2010, by SektionEins GmbH

(At least that's what I'm getting, on a Debian server)

That means people will have to build PHP from source to use Joomla on their server. I'm not sure what version of PHP most shared hosting providers are running? If an up-to-date version of PHP is required, why not go all the way and use PHP 5.4?

**Comment by eirslett** [comment]
(or whatever the package name for php is, maybe it's apt-get install php5-common libapache2-mod-php5 php5-cli)

**Comment by dongilbert** [comment]
If your host doesn't have 5.3.10 at least, you need to change hosts. There is a critical bug in previous versions that can cripple servers. 

However, we should at the very least put in the actual minimum required version for the code to operate. The good thing about having separate packages is that the minimum version doesn't need to be consistent throughout each. Someone could release a 5.4 only Joomla Package that utilizes traits if they wanted to.

**Comment by mbabker** [comment]
Off hand, I don't have where this was discussed readily available, but I know there was a discussion about what PHP version is shipped with which software currently.  In terms of web hosts, any decent host that's on PHP 5.3 is at least running the latest version.  Mac OS X 10.8 I believe ships with 5.3.13 (having a hard time getting a solid answer from Google), and many of the developer *AMP stacks are shipping with the latest PHP 5.3, if not 5.4 already.  So, older structures will need updating, but they should be updated anyways.

**Pull request closed without merging**
