### PR TITLE
Refactor GitHub API implementation

### PR DESCRIPTION
**Pull request by elkuku**
This is a follow up from https://github.com/joomla/joomla-platform/pull/1820
#### Structure amd Documentation

The API is organized using the same structure as the API documentation on GitHub

**Example**

<table class="table table-bordered table-striped">
    <tr>
        <th>Package</th>
        <th>Sub Package</th>
        <th>Method</th>
        <th>Documentation</th>
    </tr>

    <tr>
        <td>Repositories</td>
        <td></td>
        <td></td>
        <td><a href="http://developer.github.com/v3/repos/">developer.github.com/v3/<b>repos</b></a></td>
    </tr>
    <tr>
        <td><code>repositories-&gt;</code></td>
        <td></td>
        <td><code>get()</code></td>
        <td><a href="http://developer.github.com/v3/repos/#get">developer.github.com/v3/<b>repos/#get</b></a></td>
    </tr>
    <tr>
        <td>Repositories</td>
        <td>Comments</td>
        <td></td>
        <td><a href="http://developer.github.com/v3/repos/comments/">developer.github.com/v3/<b>repos/comments</b></a></td>
    </tr>
    <tr>
        <td><code>repositories-&gt;</code></td>
        <td><code>comments-&gt;</code></td>
        <td><code>get()</code></td>
        <td><a href="http://developer.github.com/v3/repos/comments/#get-a-single-commit-comment">developer.github.com/v3/<b>repos/comments/#get-a-single-commit-comment</b></a>
        </td>
    </tr>
    </tr>
</table>

**Hint:** Take a look at the <a href="http://elkuku.github.io/dox/JGithub/platform/api/packages/Joomla.html">Joomla! API Documentation</a> and compare to the <a href="http://developer.github.com/v3">GitHub API Documentation</a> (the right navigation menu).
#### Backwards compatibility

All methods have been moved:
- <a href="http://elkuku.github.io/dox/JGithub/compat-chart-old-new.html">Old vs. New Methods</a>
- <a href="http://elkuku.github.io/dox/JGithub/compat-chart-new-old.html">New vs. Old Methods</a>
#### Additional resources

<table>
<tr>
<th>Platform (complete)</th>
<th>Framework (WIP)</th>
</tr>
<tr>
<td><a href="http://elkuku.github.io/dox/JGithub/platform/api">API Doc</a></td>
<td><a href="http://elkuku.github.io/dox/JGithub/framework/api">API Doc</a></td>
</tr>
<tr>
<td><a href="http://elkuku.github.io/dox/JGithub/platform/ut-coverage/joomla_github.html">UT coverage</a></td>
<td><a href="http://elkuku.github.io/dox/JGithub/framework/ut-coverage/src_Joomla_Github.html">UT coverage</a></td>
</tr>
</table>

### CODE REVIEW

**Comment by elkuku** [comment]
This has been updated, completed, and is now "ready for review" - pls ;)

**Comment by dongilbert** [comment]
I'll try to take a look at it this weekend. Thanks for the work!

**Comment by dongilbert** [comment]
Really a very good job on this. We want to get this merged asap. However, it's no longer merge-able at the moment, so if you get that cleared up, and then update all the `since ¿` tags to `since 1.0`, we'll merge it right away.

Thanks for the work!

**Comment by elkuku** [comment]
umm... seems that there are some "duplicated commits" as well as a non related one due to a rebase :(

Is this still good to merge ?

**Comment by dongilbert** [comment]
Looks like the build passed just fine. I'll review it again when I get to an actual computer.

**Comment by dongilbert** [comment]
Thanks Nikolai!

**Pull request merged**
