### PR TITLE
clean web client

### PR DESCRIPTION
**Pull request by florianv**

### CODE REVIEW

**Comment by florianv** [comment]
Note the $instance property in Application Web is unused

**Comment by dongilbert** [comment]
I would remove it then, because Rouven did recently remove the `getInstance` methods from the Application package.

**Comment by florianv** [comment]
In fact I removed it, I was justifiying :d . Also there are some issues in Daemon, the `signal` method is static and it calls `$this->logger` and `self::instance` which is never set but it can be fixed by making it non-static.

**Comment by florianv** [comment]
I forgot to mention the detectLanguage method should parse the quality in the Accept-Language header http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4. They may not be ordered by highest qualities and if the quality is negative the language is not acceptable

**Pull request closed without merging**
