### PR TITLE
Fixing documentation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
My bad. I think the fixes are not worthy.

**Comment by dongilbert** [comment]
Worthy of what? Everything, even the small changes to help with documentation of test cases, is welcome. That's a good change. However, could you make the PR against https://github.com/joomla-framework/archive instead? That's where the code is now that you're PR is fixing.

**Comment by ghost** [comment]
Thanks. But I think that the attribute was not documented as it was a `static` variable. Noted that while browsing other tests source.

**Comment by dongilbert** [comment]
Well, its name makes it clear, but our goal is to have docblocks for everything (per our [coding standard](https://github.com/joomla/coding-standards), so if you want you can add it against the joomla-framework/archive repo, otherwise we'll get to it eventually. Thanks again!

**Comment by ghost** [comment]
Ok. I got bit confused. 

Anyway, One last question; should all my pull request targeted towards the repo you specified above, and not to this repo? Ie. should I delete this repo and clone the repo you mentioned above to send in my pull requests?

**Comment by dongilbert** [comment]
Yes - that is the new place for the Archive package, this repo is going to change.

**Comment by ghost** [comment]
Thanks. Will send the pull requests there next time onwards.

**Pull request closed without merging**
