### PR TITLE
Add alias support to DI

### PR DESCRIPTION
**Pull request by dongilbert**
Alias support is something that I've been meaning to add to the DI container. It's useful, as shown by the JTracker project needing to extend the container in order to add it themselves.

This also makes the private class properties protected so that devs can safely extend our container and still have access to the properties.

The new additions retain the 100% code coverage: http://d.pr/i/DxOc

### CODE REVIEW

**Comment by piotr-cz** [comment]
Could you add update how to use aliases to the DI documentation?

**Comment by dongilbert** [comment]
Good point - thanks for reminding me.

**Comment by dongilbert** [comment]
I've created a documentation outline, it's going to take a little bit to get it all written out. I'll post back when it's ready to be merged.

**Comment by asika32764** [comment]
I'm waiting this features for a long time.

**Comment by dongilbert** [comment]
This is ready to merge.

**Comment by piotr-cz** [comment]
Thank you! :+1:

**Pull request merged**
