### PR TITLE
Fixed missing ini_get check in the stream transport

### PR DESCRIPTION
**Pull request by SniperSister**
The missing ini_get check causes the Joomla\HTTP\Factory::getHTTP returning a transport that isn't working

### CODE REVIEW

**Comment by dongilbert** [comment]
This is a good change, but the travis build failed due to an apt-get problem.

**Comment by SniperSister** [comment]
So? What can we do about that?

**Comment by dongilbert** [comment]
Update a docblock somewhere and make another push? That will trigger another build. I'm not sure otherwise how to trigger it.

**Comment by dongilbert** [comment]
Nevermind - Travis has the ability to "restart build" which I just did. So we'll wait and see.

**Comment by dongilbert** [comment]
Hrm - still failed.

I'm looking into what else we can do here.

**Comment by mbabker** [comment]
I can look through my history and get to the repo I got that script from to
see if they've made any changes.

**Pull request merged**
